### ISSUE TITLE
Homepage-W3C : Errors on pages.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#63]
![63](https://cloud.githubusercontent.com/assets/18256652/15700141/b8bd854a-2804-11e6-9e36-e27f1bffbf78.png)

**Comment by iteano** [comment]
Still not fixed..

![Uploading 63a.png…]()

**Comment by bukssaayman** [comment]
Should be fixed now.

**Comment by iteano** [comment]
Still there's one error left.
![104](https://cloud.githubusercontent.com/assets/18256652/16002607/38d2911e-318b-11e6-97c9-df6c05d779de.png)

**Comment by bukssaayman** [comment]
Added missing alt tag.

**Comment by roseliesromeo** [comment]
Not fixed in the following pages
http://quality-traffic-management-imp.stage.titanweb.com.au/
W3C Error: https://validator.w3.org/nu/?doc=http%3A%2F%2Fquality-traffic-management-imp.stage.titanweb.com.au%2F
http://quality-traffic-management-imp.stage.titanweb.com.au/service/traffic-management/
W3C Error: https://validator.w3.org/nu/?doc=http%3A%2F%2Fquality-traffic-management-imp.stage.titanweb.com.au%2Fservice%2Ftraffic-management%2F
http://quality-traffic-management-imp.stage.titanweb.com.au/service/electrical/
W3C Errorhttps://validator.w3.org/nu/?doc=http%3A%2F%2Fquality-traffic-management-imp.stage.titanweb.com.au%2Fservice%2Felectrical%2F
http://quality-traffic-management-imp.stage.titanweb.com.au/faqs/
https://validator.w3.org/nu/?doc=http%3A%2F%2Fquality-traffic-management-W3C Errorimp.stage.titanweb.com.au%2Ffaqs%2F

**Comment by bukssaayman** [comment]
Hi Roselie
I can't find any errors on any of the pages you listed above. Please look at my attached document.
[qtm.pdf](https://github.com/titan-cebu/Quality-Traffic-Management/files/322713/qtm.pdf)
